return {
    '.NET is called .NET so that it wouldn’t show up in a UNIX directory listing.',
    '99 little bugs in the code. 99 little bugs in the code. Take one down, patch it around. 127 little bugs in the code …',
    'A SQL query goes into a bar, walks up to two tables, and asks, ‘Can I join you?’',
    'A good programmer is someone who always looks both ways before crossing a one-way street.',
    'A good programmer is someone who always looks both ways before crossing a one-way street.',
    'A program is never less than 90% complete and never more than 95% complete.',
    'A son asked his father (a programmer) why the sun rises in the east, and sets in the west. His response? It works, don’t touch!',
    'A system administrator has two problems: 1. Dumb users. 2. Smart users.',
    'ASCII stupid question, get a stupid ANSI.',
    'Algorithm: Word used by programmers when they don’t want to explain what they did.',
    'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.',
    'Always code as if the person who ends up maintaining your code will be a violent psychopath who knows where you live.',
    'Before software can be reusable it first has to be usable.',
    'C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do, it blows your whole leg off.',
    'C programmers never die. They are just cast into void.',
    'C++: An octopus made by nailing extra legs onto a dog.',
    'C++: Where your friends have access to your private members.',
    'COBOL programmers understand why women hate periods.',
    'Computers are fast; programmers keep it slow.',
    'Computers are good at following instructions but not at reading your mind.',
    'Copy-and-Paste was programmed by programmers for programmers actually.',
    'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.',
    'Deleted code is debugged code.',
    'Documentation is like sex: When it is bad, it is better than nothing. When it is good, it is really, really good.',
    'Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.',
    'God is real … unless declared integer.',
    'Hardware is made to last. Software is made to change. Change is the only thing that lasts. Software wins.',
    'How many programmers does it take to change a light bulb? None, that’s a hardware problem.',
    'I have always wished that my computer would be as easy to use as my telephone. My wish has come true. I no longer know how to use my telephone.',
    'I have not failed. I’ve just found 10,000 ways that won’t work.',
    'I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing.',
    'If Java had true garbage collection, most programs would delete themselves upon execution.',
    'If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.',
    'If debugging is the process of removing bugs, then programming must be the process of putting them in.',
    'If debugging is the process of removing software bugs, then programming must be the process of putting them in.',
    'If the box says, ‘This software requires Windows XP or better,’ does that mean it’ll run on Linux?',
    'If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl programs.',
    'In C we had to code our own bugs. In C++ we can inherit them.',
    'In a room full of top software designers, if two agree on the same thing, that’s a majority.',
    'In a software project team of ten, there are probably three people who produce enough defects to make them net-negative producers.',
    'In order to understand recursion, one must first understand recursion.',
    'In theory, there ought to be no difference between theory and practice. In practice, there is.',
    'It compiles; ship it.',
    'It works on my machine.',
    'It’s a curious thing about our industry: not only do we not learn from our mistakes, but we also don’t learn from our successes.',
    'It’s not a bug — it’s an undocumented feature.',
    'I’ve finally learned what upward compatible means. It means we get to keep all our old mistakes.',
    'JavaScript logic: 0 == "0" and 0 == []; therefore, "0" != []',
    'Keyboard Failure. Press F1 to continue.',
    'Knock, knock … Who’s there? … *very long pause* … Java.',
    'Linux is only free if your time has no value.',
    'May your programming be fun, and you vimming be quick',
    'Measuring programming progress by lines of code is like measuring aircraft building progress by weight.',
    'Most of you are familiar with the virtues of a programmer. There are three, of course: laziness, impatience, and hubris.',
    'No code has zero defects.',
    'One man’s crappy software is another man’s full-time job.',
    'One of the main causes of the fall of the Roman Empire was that lacking zero, they had no way to indicate successful termination of their C programs.',
    'One: Demonstrations always crash. And two: The probability of them crashing goes up exponentially with the number of people watching.',
    'Perl: The only language that looks the same before and after RSA encryption.',
    'Potential partners are like internet domain names — the ones I like are already taken.',
    'Programmer: A machine that turns coffee into code.',
    'Programmer’s partner: ‘Are you going to sit and type in front of that thing all day, or are you going out with me?’ Programmer: ‘Yes.’',
    'Programming can be fun, and so can cryptography; however, they should not be combined.',
    'Programming is like sex. One mistake and you have to support it for the rest of your life.',
    'Programming made the impossible possible. You can have a null object and a constant variable.',
    'Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning.',
    'Python: Executable pseudocode. Perl: Executable line noise.',
    'Q: How different are C and C++? A: 1. Because C — C++ = 1.',
    'Q: If 1 is true and 0 is false? A: 1.',
    'Q: Is the glass half-full or half-empty? A: The glass istwice as big as it needs to be.',
    'Q: What did the Java code say to the C code? A: You’ve got no class.',
    'Ready, fire, aim: thefast approach to software development. Ready, aim, aim, aim, aim: the slow approach to software development.',
    'Remember that there is no code faster than no code.',
    'Russian roulette: [ $[ $RANDOM % 6 ] == 0 ] && rm -rf / || echo *Click*',
    'Saying that Java is good because it works on all platforms is like saying anal sex is good because it works on all genders.',
    'Should one learn Advanced BASIC programming language?',
    'Software and cathedrals are much the same — first we build them, then we pray.',
    'Software undergoes beta testing shortly before it’s released. Beta is Latin for still doesn’t work.',
    'Some people when confronted with a problem think, "I know, I’ll use regular expressions.” Now they have two problems.',
    'The best method for accelerating a computer is the one that boosts it by 9.8 m/s2.',
    'The best performance improvement is the transition from the nonworking state to the working state.',
    'The best thing about a boolean is even if you are wrong, you are only off by a bit.',
    'The best way to get accurate information on Usenet is to post something wrong and wait for corrections.',
    'The cheapest, fastest, and most reliable components are those that aren’t there.',
    'The computer was born to solve problems that did not exist before.',
    'The evolution of languages: FORTRAN is a nontyped language. C is a weakly typed language. Ada is a strongly typed language. C++ is a strongly hyped language.',
    'The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.',
    'There are 10 kinds of people in the world: Those who know binary and those who don’t.',
    'There are only two hard things in computer science: cache invalidation and naming things.',
    'There are only two kinds of programming languages out there. The ones people complain about and the ones no one uses.',
    'There are only two kinds of programming languages: those people always bitch about and those nobody uses.',
    'There are two ways to write error-free programs; only the third one works.',
    'There is an easy way and a hard way. The hard part is finding the easy way.',
    'There is no Ctrl-Z in life.',
    'There’s no obfuscated Perl contest because it’s pointless.',
    'There’s no place like 127.0.0.1.',
    'To understand what recursion is, you must first understand recursion.',
    'Two bytes meet. The first byte asks, ‘Are you ill?’ The second byte replies, ‘No, just feeling a bit off.’',
    'UNIX is simple. It just takes a genius to understand its simplicity.',
    'UNIX is user friendly. It’s just very particular about who its friends are.',
    'UNIX was not designed to stop people from doing stupid things, because that would also stop them from doing clever things.',
    'Walking on water and developing software from a specification are easy if both are frozen.',
    'What’s the object-oriented way to get wealthy? Inheritance.',
    'When I wrote this code, only God and I understood what I did. Now only God knows.',
    'When all else fails … reboot.',
    'When we had no computers, we had no programming problems either.',
    'When your hammer is C++, everything begins to look like a thumb.',
    'Whitespace is never white.',
    'Why do Java programmers have to wear glasses? Because they don’t C#.',
    'Why programmers like UNIX: unzip, strip, touch, finger, grep, mount, fsck, more, yes, fsck, fsck, fsck, umount, sleep.',
    'William Shakespeare’s question 2B OR NOT 2B = FF',
    'Without C we only have Obol, Pasal, and BASI.',
    'Without requirements or design, programming is the art of adding bugs to an empty text file.',
    'You’ll surely have fun when programming Kotlin, promised.',
    'oodoo Programmin',
    'Norwegians are so fast in Vim because their ancestors are vi-kings.',
}
